# Generated by Django 2.0.7 on 2019-09-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190831_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_tile',
            new_name='create_time',
        ),
    ]
